# Generated by Django 5.0 on 2024-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_alter_officer_address_alter_officer_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(blank=True, choices=[('Recruit Constable', 'Recruit Constable'), ('Constable', 'Constable'), ('Corporal', 'Corporal'), ('Sergeant', 'Sergeant'), ('Sergeant Major', 'Major'), ('Inspector', 'Inspector')], max_length=100),
        ),
    ]
