# Generated by Django 5.0.6 on 2024-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_alter_officer_address_alter_officer_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='duty_status',
            field=models.CharField(choices=[('On Duty', 'On Duty'), ('Off Duty', 'Off Duty')], default='On Duty', max_length=10),
        ),
    ]
