# Generated by Django 5.0 on 2024-05-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_alter_officer_rank'),
        ('officers', '0003_officer_duty_status'),
    ]

    operations = [
    ]
