# Generated by Django 5.0.6 on 2024-05-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.crimetype')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('event_date', models.DateTimeField()),
                ('location_of_crime', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('witnesses', models.TextField()),
                ('known_suspects', models.TextField()),
                ('arrested_suspects', models.TextField()),
                ('case_status', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('closed', 'Closed')], max_length=12)),
                ('pictures_of_evidence', models.ImageField(null=True, upload_to='images/')),
                ('associated_case_files', models.ManyToManyField(blank=True, to='cases.criminalcase')),
                ('case_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
                ('crime_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.crimesubcategory')),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.crimetype')),
            ],
        ),
    ]
