# Generated by Django 5.0 on 2024-05-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalcase',
            name='case_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officers.officer'),
        ),
    ]
