# Generated by Django 5.0 on 2024-05-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_criminalcase_case_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalcase',
            name='arrested_suspects',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='criminalcase',
            name='known_suspects',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='criminalcase',
            name='pictures_of_evidence',
            field=models.ImageField(null=True, upload_to='src/images/'),
        ),
        migrations.AlterField(
            model_name='criminalcase',
            name='witnesses',
            field=models.CharField(max_length=255),
        ),
    ]
