# Generated by Django 5.0 on 2024-05-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_criminalcase_arrested_suspects_and_more'),
        ('criminals', '0006_merge_20240530_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalcase',
            name='associated_case_files',
        ),
        migrations.AddField(
            model_name='criminalcase',
            name='associated_case_files',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminals.criminalrecord'),
        ),
    ]
