# Generated by Django 5.0 on 2024-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficers',
            name='sex',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
