# Generated by Django 5.0 on 2024-05-24 21:18

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_policeofficers_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('badge_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('tribe', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('nin', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=100)),
                ('distinctive_features', models.TextField(default='Scars, Tribal marks, Tattoos, Piercings, etc.')),
                ('next_of_kin', models.CharField(max_length=255)),
                ('finger_print', models.ImageField(upload_to='images/')),
                ('mugshot', models.ImageField(upload_to='images/')),
                ('known_aliases', models.CharField(max_length=255)),
                ('associates', models.CharField(max_length=255)),
                ('case_number', models.CharField(default=app.models.generate_case_number, max_length=9, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='policeofficers',
            old_name='Area',
            new_name='area',
        ),
        migrations.AddField(
            model_name='policeofficers',
            name='nationality',
            field=models.CharField(default='Nigerian', max_length=255),
        ),
    ]
