# Generated by Django 5.0 on 2024-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addnewofficer_criminalrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewofficer',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
