# Generated by Django 5.0 on 2024-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_addnewofficer_password'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewofficer',
            name='groups',
            field=models.ManyToManyField(related_name='app_add_new_officer_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='addnewofficer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addnewofficer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addnewofficer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='addnewofficer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='addnewofficer',
            name='user_permissions',
            field=models.ManyToManyField(related_name='app_add_new_officer_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='addnewofficer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
