# Generated by Django 5.0 on 2024-05-28 20:19

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_addnewofficer_groups_addnewofficer_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default=app.models.generate_case_number, max_length=9, unique=True)),
                ('event_date', models.DateTimeField()),
                ('crime_type', models.CharField(max_length=255)),
                ('location_of_crime', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('associated_case_files', models.FileField(upload_to='files/')),
                ('witnesses', models.CharField(max_length=255)),
                ('known_suspects', models.CharField(max_length=255)),
                ('arrested_suspects', models.CharField(max_length=255)),
                ('case_status', models.CharField(max_length=100)),
                ('pictures_of_evidence', models.ImageField(upload_to='images/')),
                ('associated_criminals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criminalrecord')),
                ('case_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.policeofficers')),
            ],
        ),
    ]
