# Generated by Django 5.0 on 2024-05-28 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_crimesubcategory_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminalrecord',
            old_name='height',
            new_name='height_in_m',
        ),
        migrations.RenameField(
            model_name='criminalrecord',
            old_name='weight',
            new_name='weight_in_kg',
        ),
        migrations.AlterField(
            model_name='case',
            name='associated_case_files',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='case',
            name='associated_criminals',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.criminalrecord'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_officer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.policeofficers'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pictures_of_evidence',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='finger_print',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='nin',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
