# Generated by Django 5.0.6 on 2024-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('crime_committed', models.CharField(max_length=255)),
                ('date_of_arrest', models.DateField(blank=True, default=None, null=True)),
                ('is_incarcerated', models.BooleanField(default=False)),
            ],
        ),
    ]
