# Generated by Django 5.0 on 2024-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0002_criminalrecord_delete_criminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecord',
            name='crime_type',
            field=models.CharField(default='Grand Larceny', max_length=100),
        ),
    ]
