# Generated by Django 5.0.6 on 2024-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0004_rename_crime_type_criminalrecord_crime_committed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalrecord',
            name='crime_committed',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='finger_print',
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),

        migrations.AlterField(
            model_name='criminalrecord',
            name='distinctive_features',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Widower', 'Widower'), ('Celibate', 'Celibate')], default='Single', max_length=10),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to='src/images/'),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional Worshippers', 'Traditional Worshippers'), ('Others', 'Others')], max_length=100),
        ),
    ]
