# Generated by Django 5.0 on 2024-05-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0005_login'),
        ('criminals', '0005_remove_criminalrecord_crime_committed_and_more'),
    ]

    operations = [
    ]
