# Generated by Django 5.0 on 2024-05-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_criminalcase_associated_case_files'),
        ('criminals', '0006_merge_20240530_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecord',
            name='associated_cases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.criminalcase'),
        ),
    ]
