# Generated by Django 5.0 on 2024-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0007_criminalrecord_associated_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalrecord',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
