# Generated by Django 5.0 on 2024-06-01 09:22

import criminals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0008_alter_criminalrecord_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalrecord',
            name='case_number',
            field=models.CharField(default=criminals.models.generate_case_number, max_length=10, unique=True),
        ),
    ]
