# Generated by Django 5.0.6 on 2024-06-06 22:34

import criminals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0009_alter_criminalrecord_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalrecord',
            name='case_number',
            field=models.CharField(default=criminals.models.generate_case_number, max_length=9, unique=True),
        ),
    ]
